### ISSUE TITLE
Two Factor Authentication SNAFU

### ISSUE THREAD

**Issue by JesseScott** [hanford/Mobile-Github-Client#1]
Great Idea, but its broke :cry: 

Leaving this here rather than give a 1-Star review on the app store... 

**When I verify my authentication code, the app just returns me to the Login screen again... endless cycle.**

_iPod Touch 2nd Gen, iOS 8.1.2, App Version 1.0.9_

**Comment by hanford** [comment]
Thanks for the feedback - I have an update that is "Waiting for review" that fixes authentication. Should be out soon!

**Comment by JesseScott** [comment]
Ok Rad, thanks for the quick response. 
Will close this if I can verify the fix...

**Comment by hanford** [comment]
I was just notified that the app is "ready for sale" it should be rolling out in the next couple of hours, keep an eye out for version 1.1.1

**Comment by JesseScott** [comment]
I'm In!

![2014-12-17 18 46 01](https://cloud.githubusercontent.com/assets/669104/5482865/068e721a-861d-11e4-81f5-3b62f4b1b403.png)
